### ISSUE TITLE
Using Bentoml v 1.2.10, cant connect to host network and fails to download the debian

### ISSUE THREAD

**Issue by OriAlpha** [bentoml/BentoVLLM#30]
Hallo, 

```
service: "service:VLLM"
labels:
  owner: bentoml-team
  stage: demo
include:
- "*.py"
- "bentovllm_openai/*.py"
python:
  requirements_txt: "./requirements.txt"
  lock_packages: false
docker:
    distro: debian
    python_version: "3.10"
    cuda_version: "12.1.1"
```
adding: 
```
docker:
    distro: debian
    python_version: "3.10"
    cuda_version: "12.1.1"
    network_mode: "host"
```
Also deosnt work, containering does work at all. There just no documation about it how could we do it
